version: 0.0
os: linux
files:
  - source: demoRepo-main/index.html
    destination: demoRepo-main/var/www/html/
hooks:
  BeforeInstall:
    - location: demoRepo-main/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: demoRepo-main/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: demoRepo-main/scripts/stop_server
      timeout: 300
      runas: root

